import { jsPDF } from "jspdf";

const BRAND = "#319bff";
const DANGER = "#ef4444";
const SUCCESS = "#10b981";
const SLATE = "#0f172a";
const MUTED = "#64748b";

function fmt(n) {
  return Number(n).toFixed(1);
}

export function downloadReportPDF(result) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 56;

  // Header band
  doc.setFillColor(11, 16, 32);
  doc.rect(0, 0, W, 80, "F");
  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("DeepFake AI Detector", 40, 38);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor("#cbd5e1");
  doc.text("ResNeXt + LSTM + MobileViT · Analysis Report", 40, 56);
  doc.setTextColor(SLATE);

  y = 110;

  // Verdict block
  const isFake = result.label === "FAKE";
  const color = isFake ? DANGER : SUCCESS;
  doc.setDrawColor(color);
  doc.setFillColor(color);
  doc.roundedRect(40, y, W - 80, 64, 10, 10, "S");
  doc.setFontSize(11);
  doc.setTextColor(MUTED);
  doc.text("VERDICT", 56, y + 22);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(color);
  doc.text(isFake ? "Likely manipulated" : "Looks authentic", 56, y + 46);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(SLATE);
  doc.text(`${fmt(result.confidence * 100)}% confidence`, W - 56, y + 46, {
    align: "right",
  });
  y += 90;

  // Metadata table
  const rows = [
    ["File", result.filename],
    ["Size", result.size_bytes ? `${(result.size_bytes / 1024 / 1024).toFixed(2)} MB` : "—"],
    ["Model", result.model],
    ["Demo mode", result.demo_mode ? "Yes" : "No"],
    ["Frames analyzed", `${result.frames_analyzed} / sequence ${result.sequence_length}`],
    ["Faces detected", String(result.faces_detected)],
    ["Inference time", `${(result.elapsed_ms / 1000).toFixed(2)} s`],
    ["Real probability", `${fmt(result.real_prob * 100)}%`],
    ["Fake probability", `${fmt(result.fake_prob * 100)}%`],
    ["Generated", new Date().toLocaleString()],
  ];

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(SLATE);
  doc.text("Analysis details", 40, y);
  y += 14;
  doc.setLineWidth(0.5);
  doc.setDrawColor("#e2e8f0");
  doc.line(40, y, W - 40, y);
  y += 12;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  rows.forEach(([k, v]) => {
    doc.setTextColor(MUTED);
    doc.text(k, 50, y + 12);
    doc.setTextColor(SLATE);
    doc.text(String(v), W - 50, y + 12, { align: "right" });
    y += 22;
  });

  y += 8;

  // Per-frame chart (simple bar plot)
  const data = result.per_frame_fake_prob || [];
  if (data.length) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(SLATE);
    doc.text("Per-frame fake probability", 40, y);
    y += 8;
    const chartX = 40;
    const chartW = W - 80;
    const chartY = y + 8;
    const chartH = 110;

    doc.setDrawColor("#e2e8f0");
    doc.rect(chartX, chartY, chartW, chartH, "S");

    doc.setDrawColor("#94a3b8");
    doc.setLineWidth(0.4);
    doc.setLineDashPattern([2, 2], 0);
    doc.line(chartX, chartY + chartH / 2, chartX + chartW, chartY + chartH / 2);
    doc.setLineDashPattern([], 0);

    const barW = chartW / data.length;
    data.forEach((p, i) => {
      const h = chartH * p;
      const x = chartX + i * barW;
      const yy = chartY + (chartH - h);
      doc.setFillColor(p >= 0.5 ? DANGER : SUCCESS);
      doc.rect(x + 0.5, yy, Math.max(0.5, barW - 1), h, "F");
    });

    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text("0%", chartX - 4, chartY + chartH + 2, { align: "right" });
    doc.text("100%", chartX - 4, chartY + 8, { align: "right" });
    doc.text(`Frames 1 → ${data.length}`, chartX + chartW, chartY + chartH + 14, {
      align: "right",
    });
    y = chartY + chartH + 36;
  }

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text(
    "This report was generated by the DeepFake AI Detector SPA. Predictions are probabilistic and should not be used as the sole basis for legal decisions.",
    40,
    doc.internal.pageSize.getHeight() - 32,
    { maxWidth: W - 80 },
  );
  doc.setTextColor(BRAND);
  doc.text("deepfake-ai-detector", W - 40, doc.internal.pageSize.getHeight() - 32, {
    align: "right",
  });

  const filename = `deepfake-report-${result.upload_id || Date.now()}.pdf`;
  doc.save(filename);
}
